---
apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: jenkins
  namespace: gibbons-system
  annotations:
    flux.weave.works/automated: "false"
spec:
  releaseName: jenkins
  chart:
    repository: https://kubernetes-charts.storage.googleapis.com/
    name: jenkins
    version: 0.33.0
  values:
    Master:
      UseSecurity: true
      HostName: jenkins.br0tbox.de
      Ingress: 
        ApiVersion: extensions/v1beta1
        Annotations: 
          kubernetes.io/ingress.class: "nginx"    
          certmanager.k8s.io/cluster-issuer: "letsencrypt-prod"
          certmanager.k8s.io/acme-challenge-type: http01
        TLS:
          - hosts:
            - jenkins.br0tbox.de
            secretName: jenkins-cert-tls-1
      ServiceType: ClusterIP
    rbac:
      install: true